# .pre-commit-config.yaml
# to make a commit without a pre-commit hook you can use 'git commit --no-verify -m "message"' 
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0  # this is optional, use `pre-commit autoupdate` to get the latest rev!
    hooks:
    -   id: check-yaml
-   repo: https://github.com/pycqa/flake8
    rev: '2f90d073891b0b8777915383c35ecf8838680264'  # Use the latest version available
    hooks:
    -   id: flake8
        args: ['--max-line-length=120', '--ignore=F401,E402,E266,W293']
#-   repo: local
#    hooks:
#    -   id: pytest
#        name: pytest
#        language: python
#        entry: pytest
