name: Build Vite Pages

on:
  push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: 'The-Syntax-Sorcerers/ava'

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install --prefix client

      - name: Build project
        run: npm run build --prefix client

      - name: Check for Staged Changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add client/dist -f
          if git diff --cached --quiet; then
            echo "No changes staged for commit. Skipping commit and push."
          else
            git commit -m "[bot] CI: Vite-Build"
            git push
          fi
        if: success()
