name: Build and Deploy

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: 'The-Syntax-Sorcerers/ava'

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install --prefix client

      - name: Build project
        run: npm run build --prefix client

      # - name: Store dist output
      #   run: |
      #     mkdir -p client/dist
      #     cp -r client/dist/* client/backup/dist/
      #   if: success()

      - name: Commit and push changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add client/dist
          git commit -m "Built Static Dist Files"
          git push
        if: success()
